### ISSUE TITLE
Only four information are in event in on_crash or before_send handler. Exception and other information is missing.

### ISSUE THREAD

**Issue by funeetop** [getsentry/sentry-native#1015]
**Description**
I am using sentry-native 0.6.7, with in-build crashpad backend. When I try to filter/get some basic information from the event parameter, only four types of information can I  at on_crash and before_send handler. 
{"event_id":"77e765e5-7adb-47dc-6873-38797083d7c0","timestamp":"2024-06-24T09:54:48.918000Z","platform":"native","level":"fatal"}
But in sentry dash board I can see full calling-stack of exception.
In https://docs.sentry.io/platforms/native/guides/crashpad/configuration/filtering/ 
examples are show get information about exception. 
I cannot get that information.
Is the information removed in recent release or am I using sentry wrong?
Please help!

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

- OS: Windows 11, 64-bit
- Compiler:  MSVC 22
- CMake version and config: [e.g. 3.30.0, SENTRY_BACKEND=crashpad]

**Steps To Reproduce**

static sentry_value_t
on_crash_callback(
    const sentry_ucontext_t *uctx, sentry_value_t event, void *closure)
{
    auto serJson = sentry_value_to_json(event);
    std::cout << serJson;
    sentry_string_free(serJson);
    return event;
}
int main(int argc, char *argv[])
{
    //setup sentry
    auto options = sentry_options_new();
    sentry_options_set_dsn(options, SENTRY_URL);
    sentry_options_set_database_path(options, ".sentry-native");
    sentry_options_set_release(options, PROJECT_NAME "@" COMMIT_HASH);
    sentry_options_set_debug(options, 1);
    sentry_options_set_on_crash(options, on_crash_callback, nullptr);
    sentry_init(options);
    
    auto *crash = reinterpret_cast<volatile int *>(0);
    *crash = 0;
    sentry_close();
}

**Log output**
{"event_id":"77e765e5-7adb-47dc-6873-38797083d7c0","timestamp":"2024-06-24T09:54:48.918000Z","platform":"native","level":"fatal"}

**Comment by supervacuus** [comment]
Hi @funeetop. None of the minidump-generating backends (`crashpad` and `breakpad`) allow you to inspect your stack traces in the hooks locally. These backends generate the dumps only after you return the event from the hooks and never touch the generated minidumps before sending. The minidumps processing is part of the backend; thus, no contents (threads, stack traces, registers, etc.) will be available in the client.

The `inproc` backend allows you to inspect the stack trace. Still, since the client symbolication (if enabled) only happens when preparing events for sending, which occurs after invoking the hook, it will only show a list of instruction addresses.

For all backends, the handler applies scope data only while preparing for sending, which means that no tracked meta-data will be visible in the hook's event argument.

Most users set up hooks to act on the crashes (like flushing logs for attachment) or discard them for environmental reasons, which they typically retrieve via the `closure` parameter. Do you have specific event data you want to filter `on_crash`?

**Comment by supervacuus** [comment]
If you are looking for raw exception/signal data, the hook receives these via the `sentry_ucontext_t *uctx` parameter, just in case this is unclear:

https://github.com/getsentry/sentry-native/blob/37bf733697e4ce7481bc4630300617768d006a4e/include/sentry.h#L493-L505
