### ISSUE TITLE
Does Sentry Native support frame pointers stack unwinding?

### ISSUE THREAD

**Issue by gawen** [getsentry/sentry-native#115]
Hello,

I wish to unwind stack traces locally when a crash happen on a Android ARM{32,64} device. My binary is compiled *with* frame pointers.

For my project, when a crash happens, sentry-native is able to only get the first frame with `libunwindstack`, but fail to get all of them.

Reading `libunwindstack`, I see it relies on DWARF symbols to unwind a stack trace. I unfortunately cannot ship my binary with DWARF symbols as the binary would be too big.

I would expect Sentry native (with `libunwindstack`) to follow frame pointers to unwind a stack trace, but it doesn't work for me, and I cannot find any mention of this in `libunwindstack`.

Does it support frame pointer stack unwinding? If yes, is there something to enable? Or did I miss something?

Thank you for your help!

**Comment by mitsuhiko** [comment]
I'm assuming this is for Android? The unwinder story is not great on Android in general and we're currently using `libunwindstack` because that's the only thing that is really somewhat supported on Android these days. It should be able to unwind with `eh_frame` info which is in the binary and does not require DWARF debug data.

**Comment by Swatinem** [comment]
@gawen In theory, we have support for multiple unwinders, however only `libunwindstack` is used on android.
We will release version `0.2` later today. Can you please check again with that version and reopen the issue if necessary.
