### ISSUE TITLE
[CMake] Tests are compiled by default when sentry-native is added as a subdirectory

### ISSUE THREAD

**Issue by Amphaal** [getsentry/sentry-native#193]
IMO it should not happen in that specific usecase. https://cliutils.gitlab.io/modern-cmake/chapters/testing.html shows a great way of fixing this without having to define specific options manually (SENTRY_BUILD_TESTS, SENTRY_BUILD_EXAMPLES)

**Comment by Swatinem** [comment]
CC @madebr since you added those options.

I agree this needs improvement, which I also noticed when trying to uplift this into `sentry-android` https://github.com/getsentry/sentry-android/pull/305

We also wanted to originally remove the complete test folder from the release archive, but if you build from the release archive, cmake fails if the tests are not there -_-

**Comment by madebr** [comment]
Imho, releases should have some sort of test included.

Ideally, this test should test the binaries that are used in the final binary,
and not re-compiled as is done currently because the compiler cannot be trusted. :smile:
