### ISSUE TITLE
Error building a static version in macOS 

### ISSUE THREAD

**Issue by david-antiteum** [getsentry/sentry-native#204]
Hi,

While doing a port for Vcpkg I have found a build problem in macOS (10.15.4 Xcode 11.4) that can be reproduce with this commands:

```
git clone --recurse-submodules https://github.com/getsentry/sentry-native.git
cd sentry-native
cmake -B build -DSENTRY_BACKEND=crashpad -DSENTRY_TRANSPORT=curl -DSENTRY_BUILD_TESTS=OFF -DSENTRY_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
```

CMake error is:

```
CMake Error at CMakeLists.txt:136 (install):
  install TARGETS given target "getopt" which does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:264 (sentry_install)
```

Shared build compiles with no issues.

Thanks,

David

**Comment by Swatinem** [comment]
Ah… So these are only defined/built on windows/msvc:

https://github.com/getsentry/crashpad/blob/4ec46c337905a10f1690ef57594daa11d6e08644/CMakeLists.txt#L91-L94

So need to make it conditional here as well:

https://github.com/getsentry/sentry-native/blob/58b541ff2cd47ad7545282753e4c9b0de25eacd2/CMakeLists.txt#L263-L267

I will take care of this tomorrow…

**Comment by Swatinem** [comment]
CMake!!! 😭 

Seems like this is not as easy as I thought. I now run into the following error:

```
CMake Error in external/crashpad/compat/CMakeLists.txt:
  Target "crashpad_compat" INTERFACE_SOURCES property contains path:

    "/Users/swatinem/Coding/sentry-native/external/crashpad/compat/non_elf/elf.h"

  which is prefixed in the source directory.
```

The crashpad/compat sources are prefix with the absolute directory, because if they are not, I get other errors. (oh, and I also saw that `list transform` is also not supported on our low cmake 3.10 target anyway -_-)
I fiddled around with this a bit, but I’m completely lost, and don’t really want to waste too much time with this.

@madebr @Amphaal You two seem to have a bit more cmake experience than me, maybe one of you can help me out here?

**Comment by david-antiteum** [comment]
I know, my plan was to fix it in a PR :) but I give up.

Ah, the vcpkg port is here:
https://github.com/david-antiteum/vcpkg-ports/tree/master/ports/sentry

Not finished due to this problem. But in any case, the idea is not to use submodules at all. Any dependencies must be external and handled by vcpkg. But crashpad is not yet in vcpkg and I was in a hurry :)

Thanks.

**Comment by Swatinem** [comment]
We maintain a fork of crashpad which has attachment support, otherwise there is no way to actually upload all the metadata that you are setting with the various APIs. Apart from that, crashpad also has no official cmake support either :-(

**Comment by david-antiteum** [comment]
I can add your version to vcpkg, I just takes me 5 minutes or 5 days, depending of the cmake on it :)

**Comment by madebr** [comment]
The problem is indeed that these targets are defined in a submodule.
I added `getopt` to the list of installed targets because it is/was required by crashpad.
But since crashpad can change at any point, the place to install these are in the cmake scripts of these modules.

Ideally, all submodules must have a cmake script equivalent to sentry-native.
That way, dependencies can be added as a git submodule (using `add_subdirectory`) or as a system library (using `find_package`).

**Comment by jblazquez** [comment]
I'm also encountering this issue. I worked around it with a minor change (see #205) and by disabling the install target, then installing manually. I would like to fix the install target as well, but I'm not a CMake expert either.

Why is this the `crashpad_compat` library defined differently on Mac than on other platforms?

https://github.com/getsentry/crashpad/blob/4ec46c337905a10f1690ef57594daa11d6e08644/compat/CMakeLists.txt#L84-L91

**Comment by Swatinem** [comment]
On mac, it is a "header only" lib, so there is no actual code generated from it. And defining it as `INTERFACE` was the way I found to make this work in cmake.
