### ISSUE TITLE
Spurious crash/hang on macOS.

### ISSUE THREAD

**Issue by daxpedda** [getsentry/sentry-native#329]
**Description**
Unknown 😢. I am assuming there is a file locking issue with the report database.

**When does the problem happen**
During run-time

**Environment**
- OS:  Mac OS X 10.15.5
- Compiler: Clang 10 with XCode 11.5 I think (https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md)
- CMake config: `BUILD_SHARED_LIBS=OFF`

**Steps To Reproduce**
I wasn't able to reproduce it in my MacOS VM, but I have consistent hangs in a multithreaded test on MacOS running in my CI on Github Actions. I didn't file a bug report before because I really have no information.

BUT, today I got an error message:
```
[3732:23831:20200702,193603.457916:ERROR crash_report_database_mac.mm:722] open lock /Users/runner/runners/2.263.0/work/sentry-contrib-native/sentry-contrib-native/target/debug/build/sentry-contrib-native-8f341f4425594f1b/out/.sentry-native/pending/99ad220d-44e7-465e-bffe-7a74fd7d2686.dmp: Resource temporarily unavailable (35)
```
This mostly happens during a test that calls every single function that is connected to `sentry_options_t` a 100 times from a seperate thread each.
Another strange thing is that after the test fails, my CI tries to run the example next, where it always gets stuck, but the reporting stops there, so I rly have no clue what happens.

From the error message it seems to me like there is a problem obtaining a lock to the database directory, which may be because all the tests and examples I'm running use the same one.

Here are the relevant CI runs:
https://github.com/daxpedda/sentry-contrib-native/actions/runs/155771051
https://github.com/daxpedda/sentry-contrib-native/actions/runs/155780131

The test that always fails looks like this (it's in Rust):
https://github.com/daxpedda/sentry-contrib-native/blob/master/src/options.rs#L956-L1061

I realize that this issue report is lacking at best, in additions the error may not have anything to do with Sentry but with crashpad.
Thank you for looking into it anyway.

**Comment by Swatinem** [comment]
This does look weird. Your locking test code seems to be fine though. Not sure if you are not running into locking problems from the rust side though, looks like you are creating >1000 threads which all do their internal locking.

You are also setting a "random" handler/database path, which is why I’m wondering if the stdout there is not from a completely different run?

https://github.com/daxpedda/sentry-contrib-native/blob/6b5ecc4aa792bd7a83e41ed488df7788871bb875/src/options.rs#L1045-L1046

The `.sentry-native` database path is the default, if you don’t explicitly override it. It is possible that one test triggers a crash, and crashpad writes the report, then you are doing a `sentry_init` which initializes crashpad again, which then hangs. All this is done in a subprocess, so I don’t think it should hang the main process.

Whan we could do is to actually run crashpad in the *run* folder, and not the *database* folder. That way, each program start will get its own folder, so no locking needs to be performed.

**Comment by Swatinem** [comment]
Just leaving this here as a short braindump.

One crashpad handler is designed to superwise multiple processes. However, we rely heavily on attachments to attach the sentry scope and breadcrumbs.

Things we need to clear up here:
* How can we attach ourselves with an already running crashpad handler?
* Does that work correctly when we have different attachments for the different app instances?

The easy way out obviously would be to give each instance its own folder, as mentioned above. The handler is pretty low overhead so it shouldn’t be that bad.

**Comment by daxpedda** [comment]
> This does look weird. Your locking test code seems to be fine though. Not sure if you are not running into locking problems from the rust side though, looks like you are creating >1000 threads which all do their internal locking.

On top of that lock visible in the test, there is another layer of internal locking for some of these functions because of https://github.com/getsentry/sentry-native/issues/280, which was the point of this test, to make sure that this works correctly.
I will have to relieve some of this locking mechanisms in the test.
But this locking shouldn't create this error, right?
> You are also setting a "random" handler/database path, ...

You can ignore the handler path, during testing internally it will be ignored and always points to the same file: https://github.com/daxpedda/sentry-contrib-native/blob/6b5ecc4aa792bd7a83e41ed488df7788871bb875/src/options.rs#L656-L659.
> ... which is why I’m wondering if the stdout there is not from a completely different run?

You are correct I believe, the error message doesn't appear unless other tests fail too.

**Comment by daxpedda** [comment]
> Just leaving this here as a short braindump.

Is there a more specific reason why this only happens on macOS?

**Comment by Swatinem** [comment]
> Is there a more specific reason why this only happens on macOS?

I don’t know. 

> You are correct I believe, the error message doesn't appear unless other tests fail too.

So what I do in the native testsuite is to give each "unique compile options" its own directory. There are some tests that do share the database folder, and I remember I had to fix a test assertion because of that.

An easy fix, and maybe also a good way to further narrow this down would be to give each test its own database folder.

But the core issue remains that apparently crashpad can’t deal with concurrent access from multiple handlers to a single database folder that well.

I will discuss this further with the team, but I think the way we use attachments/scope/breadcrumb info means we do have to have separate handler instances, in which case it makes perfect sense to have it use separate run folders as well.

**Comment by daxpedda** [comment]
I didn't implement unique directories for my other tests yet, but I got the following:
https://github.com/daxpedda/sentry-contrib-native/runs/834531401 - which shows the error message from before

So this indicates that really only one test failed.
If it is correct that the error message is coming from that one `threaded_stress` test:
- it has a unique database folder
- it doesn't send any events (unless it crashes)
- it doesn't do anything except play around with option settings, `init` and `shutdown`

If my conclusion is correct than this means that the issue isn't a conflicting database folder, in this case?

**Comment by Swatinem** [comment]
It is indeed very weird.

1. crashpad is a subprocess, whatever it does should not mess with the parent process
2. all the options stuff in itself should indeed not crash, and if it does, well it *crashes* and does not hang there for a minute.

How fast does this test normally run in CI? I’m asking because I experienced this a lot with all kinds of different projects that CI can be extremely unreliable sometimes, and running into timeouts is a completely normal thing.

**Comment by daxpedda** [comment]
This particular test doesn't do anything, so it takes a second or two usually.
The whole test suit takes 7 min., before I started integration tests that can't run in parallel and have to do HTTP requests, the building and running of the whole test suit takes only 1 min., so the timout shouldn't be an issue.

I believe the only reason why it's hitting the timeout is because the crate I'm using to spawn unit tests in seperate processes in Rust just doesn't detect crashes properly.

**Comment by daxpedda** [comment]
The crate I'm using, [`rusty-fork`](https://github.com/altsysrq/rusty-fork), spawns these tests in a subprocess.

So the testing goes like this:
- in the main process, on different threads, unit tests are run in parallel
- the "normal" unit tests never call `init`, they call almost all functions, including `event_capture`, but `init` is never called
- in "initializing" unit tests, a subprocess is spawned, in this subprocess `init` is called and all sorts of things are done, including `event_capture` and whatnot
- one of the "intializing" unit tests, `threaded_stress`, crashes at some point, the crash doesn't get detected so in the CI it will just timeout after a while
---
- after unit tests are done, examples get tested, as far as I understand these are also subprocesses, they do NOT run in parallel
- currently examples do very very little, almost no configuration, just sending an event or two
- if the `threaded_test` fails, the examples just get stuck, forever


Just thought I make a more detailed overview of the whole process to help, I wish I could reproduce this issue myself, I know you don't have a lot to go on.
Thanks!

**Comment by daxpedda** [comment]
After lots and lots of experimenting in the CI (because I wasn't able to reproduce it locally), I found that the issue is simply that `sentry_set_context` and `sentry_remove_context` is **not thread-safe**.

That was all. You can ignore the ramblings in all my posts above 😄.
#333 is hopefully gonna fix that.

**Comment by daxpedda** [comment]
I found the same issue in a couple of other functions.
I'm still confused why this wasn't an issue on any other platform than MacOS and why I couldn't reproduce it locally.
Let's hope #333 is going to save us.

**Comment by Swatinem** [comment]
> I found that the issue is simply that `sentry_set_context` and `sentry_remove_context` is **not thread-safe**.

How so? It uses the same code as `tag` and `extra`?

Ohhhh, I get it, the scope code itself was being locked, but flushing the scope was accessing options without a lock, which I’m indeed about to fix with that PR. Well I do wish things were as easy as just have an `Arc<Mutex<ClientOptions>>` ;-)
We spent half of the week already looking *very closely* at our threading implementation, and probably the rest of the week at the locking as well ;-)

**Comment by daxpedda** [comment]
> We spent half of the week already looking _very closely_ at our threading implementation, and probably the rest of the week at the locking as well ;-)

Thank you and your team for the hard work!
Currently I'm just using a `RwLock` to make sure nothing is called at the same time.
> Well I do wish things were as easy as just have an `Arc<Mutex<ClientOptions>>` ;-)

Yeah, one day maybe we will see a RIIR of it all 🤣.

**Comment by Swatinem** [comment]
> Thank you and your team for the hard work!

Thank you as well! The work you put in is amazing, and the stresstests and issues you report are really valuable!

> Yeah, one day maybe we will see a RIIR of it all 🤣.

I’ve been saying that for some time ;-)
