### ISSUE TITLE
File attachments for Crashpad on Windows and MacOS

### ISSUE THREAD

**Issue by daxpedda** [getsentry/sentry-native#332]
I was digging through the source code and found a couple of comments suggesting that file attachments aren't supported on Windows and MacOS for Crashpad yet, is this correct?

Are there any plans to work on this? If not, I would like to attempt it myself, but I would like some guidance on the matter.

**EDIT:**
I just found this:
> - File attachments support for MacOS and Windows. Based on changes made in
  https://github.com/Youw/crashpad/, distributed with Apache 2.0 License.

I also found an implementation for it, I couldn't get it to work though. Should I convert this issue to a proper bug report than?

**Comment by Swatinem** [comment]
Upstream implemented this 1-2 weeks ago: https://chromium.googlesource.com/crashpad/crashpad/+/41456998748bd3c058f36f5d785810bf7ea7a954

We maintain our own fork for crashpad primarily for this feature since quite a long time, and I recently merged in the upstream changes and updated the mac support.

So when you build with the correct submodule / our published releases, you should be good to go already.

**Comment by daxpedda** [comment]
I'm unsure if that is what you meant, but:
> So when you build with the correct submodule / our published releases, you should be good to go already.

With the correct submodule and your published 0.3.4 release it does **not** work, but with the newest master I just tried it works just fine.
