### ISSUE TITLE
With breakpad doesn't capture NULL pointer dereferencing crash

### ISSUE THREAD

**Issue by ronggong** [getsentry/sentry-native#358]
Hi,

I compiled sentry with

`cmake -B build -DSENTRY_BACKEND=breakpad -DBUILD_SHARED_LIBS=OFF
`

This is a Windows 10 App, so I use the breakpad backend https://github.com/getsentry/sentry-native/issues/190
Also tried with inproc backend, it can't capture the crash either.

```
sentry_options_t* options = sentry_options_new();
sentry_options_set_dsn(options, "xxxx");
sentry_init(options);

SystemStats::setApplicationCrashHandler(myCrashHandler);

sentry_capture_event(sentry_value_new_message_event(
            /*   level */ SENTRY_LEVEL_INFO,
            /*  logger */ "custom",
            /* message */ "It works!"
));

unsigned char* test = NULL;
test[1000] = 'a'; //<< here it should crash
```

When there is a crash, this invokes myCrashHandler, where I put
```
void myCrashHandler(void* platformSpecificCrashData)
{
    sentry_shutdown();
}
```

The message "It works!" successfully displayed in sentry.io dashboard, but not the NULL pointer dereferencing crash. myCrashHandler gets called by this crash so that the message "It works!" could be displayed.

Thanks.

**Comment by sseyod** [comment]
@ronggong some ideas

1) remove your crash code.

a) Run the app in the debugger.  Do you see the event reported on sentry.io?
b) Run the app in release mode, from the command line. Do you see the event reported on sentry.io?

2) what happens in your debugger, if you've *not* enabled sentry? I presume that the app crashes?

Hoping that helps, Pete

**Comment by sseyod** [comment]
I also found I had to do this, I can't remember why however...

```
#define SENTRY_BUILD_STATIC 1
#include <sentry.h>
```

Pete

**Comment by ronggong** [comment]
@sseyod 
Thanks.

I removed the crash code
```
unsigned char* test = NULL;
test[1000] = 'a'; //<< here it should crash
```

And kept
```
sentry_capture_event(sentry_value_new_message_event(
            /*   level */ SENTRY_LEVEL_INFO,
            /*  logger */ "custom",
            /* message */ "It works!"
));
```

This event is reported in sentry.io.

I build now the app in release mode, I can see the "It works!" event but still not the crash.

(2) If I do not enable Sentry with sentry_init, the app crashes with the crash code apparently.

**Comment by sseyod** [comment]
@ronggong I would recommend a different approach - don't set your own crash handler.

Here is basically what I do.

```
#define SENTRY_BUILD_STATIC 1
#include <sentry.h>
#include <ShlObj.h>
#include <WinError.h>

void MyApplication::initialise (const juce::String& commandLine) {

  // ...
  sentry_options_t* options = sentry_options_new();
  sentry_options_set_release(options, "my-app-name@1.0.0");
  sentry_options_set_dsn(options, "https://your_magic_value@your_value.ingest.sentry.io/your_id");
  sentry_options_set_debug(options, 1); // This is OPTIONAL but useful for you!

  // Don't rely on the default folder - or the crashes might not be uploadable in a *packaged* application, even though it works with non-packaged application!

  char tempFolder[2048];
  tempFolder[0] = 0;
  GetTempPathA((DWORD)sizeof(tempFolder), tempFolder);
  strcat(tempFolder, "\\myapp_crashes");
  int lRes = SHCreateDirectoryExA(nullptr, tempFolder, nullptr);
  if (lRes == ERROR_FILE_EXISTS) {
    printf("DEBUG: FILE_EXISTS\n");
  } else if (lRes == ERROR_ALREADY_EXISTS) {
      printf("DEBUG: FOLDER ALREADY_EXISTS\n");
  } else if (lRes == ERROR_SUCCESS) {
    printf("DEBUG: Created folder! (ERROR_SUCCESS)\n");
  } else if (lRes == ERROR_PATH_NOT_FOUND) {
    printf("DEBUG: ERROR_PATH_NOT_FOUND ... probably an invalid path!\n");
  } else {
    printf("DEBUG: lRes=%d\n", lRes);
  }

  // Be *very* careful - the library deletes *everything* in this folder...
  sentry_options_set_database_path(options, tempFolder);

  sentry_init(options);

  //...

  // I'd suggest you defer your crash to a button press.
  // That will allow the app to run for long enough when it next starts, to upload any crash reports.
}

void MyApplication::shutdown()
{
  //...
  sentry_shutdown();
  //...
}
```

Build as release, run from command line. Look at the crash report that should be uploaded *when you restart the app*.

Please note the comments I put in. The app *must* be given time at start-up, to transfer its crash logs to the server.

When your app starts, look in the path pointed to by tempFolder. The folder should be empty.

Press your button, to make your app crash.

Look in the folder pointed to by tempFolder - it should now have a crash report in it.

Restart your app - the crash report gets loaded-up to sentry.io - you should be able to see it there.

Pete

**Comment by sseyod** [comment]
@ronggong One more tip.

Once you've build the release version of you app, and you've built the package - here is how to upload all you need for the crash reports. Make sure you do this before trying to provoke a crash, or you ** won't ** get a usable crash report.

```
rem Set build number. *** Must *** match that in you Sentry initialisation code, e.g.:
rem sentry_options_set_release(options, "my-app-name@1.0.0");

sentry-cli-Windows-x86_64.exe releases new 1.0.0

rem  upload *all* the binaries - this will automatically find what is required.
rem run it from your "Release" folder that contains your .exe file...

sentry-cli-Windows-x86_64.exe upload-dif difutil check .
```

**Comment by Swatinem** [comment]
So apart from what @sseyod said, putting the `define` in before the header to have the correct linking, and to define your own `database_path`.

From your own example, `sentry_shutdown` needs to basically be the last call in your `main` function. Also, it is only called on healthy runs. Otherwise the crash handler itself does everything.

```
SystemStats::setApplicationCrashHandler(myCrashHandler);
```

I don’t think this is correct either. Sentry should handle the crashes, so no need to override it. Once you call `sentry_init`, things should be wired up correctly.

Crashes themselves will be uploaded on the next restart with the breakpad backend. So as @sseyod said, you have to correctly set up the database directory.

**Comment by sseyod** [comment]
@Swatinem I guess that the above shows there is quite a bit missing from the documentation, that would benefit from being clarified somewhere?! It was quite a long road for me to figure everything out, and get it all working. That said - I'm now a very happy developer, and have been sharing the news on what you've done with other interested developers :-D

**Comment by ronggong** [comment]
@sseyod @Swatinem  Thanks. I understood the pipeline are:

(1) create a local folder to save the crash report
(2) when crashing, the report will be saved there
(3) when restart, sentry will look into this folder, and upload the report. Sentry needs some buffer time to upload the report.

However, is this pipeline goes against the purpose of the crash reporting? Two concerns
(1) How can we know the user will launch a second time of the app when it was crashed?
(2) If the crash happens right after the sentry init, then there is no time for sentry to upload the report?

Another question is about the database directory. Should it be a permanent directory rather than a temporary one? I assume we need to re-use it when we restart the app right?

**Comment by sseyod** [comment]
Hi @ronggong 

To answer your concerns

(1) this is the way that *all* crash reporting systems work from my experience (and I've used quite a few - AppCenter, HockeyApp, Crashlytics, and others - and there are *many* other SDKs I've not listed). Sure, if your user only uses your app once, and it crashes, you won't get the crash report. But I'd suggest that isn't a typical user behaviour, and anyhow not worth worrying about.

(2) Yes, that is correct. Again, that is how all crash reporting SDKs I've used seem to work, and TBH it doesn't particularly concern me. TBH, most crashes you'll see on early start of an application, will be ones you see with a typical debugging session. Most crashes that I see in crash reports are as a result of user behaviours that are quite complicated, which lead to app states that are quite hard to predict/cover handle with unit testing.

(3) Yes, it needs to be permanent, so that your app can find the crash reports when it next restarts :)

Hoping that helps, and I wish you well in your bug hunting!

Pete

**Comment by Swatinem** [comment]
So with crashpad, the upload happens right away from a different process. Due to the Windows 10 App restrictions, I think you are only limited to shipping a single exe. You can still however bundle all the `crashpad_handler_lib` into the same executable. I also know of cases where customers have patched the crashpad handler to actually launch a separate GUI dialog, similar to the example shown here: https://github.com/getsentry/sentry-native/pull/278#issuecomment-640264128 

So yes, uploading at the time of crash is possible somehow, but probably requires a custom solution.

**Comment by ronggong** [comment]
@sseyod  Thanks! It works when I launch the second time the app. What are these commands doing?

```
rem Set build number. *** Must *** match that in you Sentry initialisation code, e.g.:
rem sentry_options_set_release(options, "my-app-name@1.0.0");

sentry-cli-Windows-x86_64.exe releases new 1.0.0

rem  upload *all* the binaries - this will automatically find what is required.
rem run it from your "Release" folder that contains your .exe file...

sentry-cli-Windows-x86_64.exe upload-dif difutil check .
```

Do we have to run these in the windows command line?

**Comment by ronggong** [comment]
@Swatinem Just to confirm my understanding. The breakpad doesn't support upload the crash report right away after the crash, only crashpad support this, right? So the solution is to bundle the crashpad_handler_lib into the same executable.
Otherwise, if we want to use breakpad for a right away uploading, we need to launch a separate GUI after the crash.

**Comment by sseyod** [comment]
@ronggong those command upload the debug symbols - so when you have a crash uploaded, the correct debug symbols are found and you get a usable track trace. Hope that helps...

**Comment by Swatinem** [comment]
> The breakpad doesn't support upload the crash report right away after the crash, only crashpad support this, right?

Yes.

> So the solution is to bundle the crashpad_handler_lib into the same executable.

Well if you are using crashpad, and have the restriction of only being able to ship a single executable.

> Otherwise, if we want to use breakpad for a right away uploading, we need to launch a separate GUI after the crash.

That is a completely different concern. With breakpad you don’t have right-away uploading either way.
