### ISSUE TITLE
Universal binaries for Apple Silicon

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-native#396]
With the move to Apple Silicon, the macOS build should (optionally) output a universal binary to support both the current amd64 and arm64e architectures. 

We will likely have to expose a new CMake build option and then shell out to `lipo` as described here:
https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

**Comment by Swatinem** [comment]
This can be done using CMake flags and is documented in the README.

**Comment by dacrome** [comment]
But this only works when I build sentry as dynamic lib, not as a static lib. I get multiple errors when I build my app:

```
Undefined symbols for architecture arm64:
  "base::FilePath::FilePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
  crashpad_backend_startup(sentry_backend_s*, sentry_options_s const*) in libsentry.a(sentry_backend_crashpad.o)
  ...
  "_curl_version_info", referenced from:
      _sentry__curl_transport_start in libsentry.a(sentry_transport_curl.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I run the following command to build sentry-native:

```
cmake -B xcodebuild -GXcode \
      -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
      -DSENTRY_BUILD_TESTS=OFF \
      -DSENTRY_BUILD_EXAMPLES=OFF \
      -DBUILD_SHARED_LIBS=OFF \
      -DSENTRY_BUILD_SHARED_LIBS=OFF
xcodebuild build -project xcodebuild/Sentry-Native.xcodeproj
```

Maybe I miss something?

**Comment by supervacuus** [comment]
Hi @dacrome, thanks for the report. This should work fine when building static libs. Unfortunately, I can't reproduce your issue. It might be that your `arm64` toolchain is missing a curl library.

**Comment by dacrome** [comment]
@supervacuus thanks for your answer!

Finally I was able to build the static lib. Currently we are not using cmake, we are using the JUCE framework and [a tool called Projucer](https://docs.juce.com/master/tutorial_manage_projucer_project.html) where we have to set everything correctly (of course in cmake we have to do also, but I think it would be easier)

The problem was that I only linked to the sentry lib and not these crashpad libs:

```
crashpad_client
crashpad_handler_lib
crashpad_minidump
crashpad_snapshot
crashpad_tools
crashpad_util
mini_chromium
```

Do I need to add them all?

First I run the xcode generator commands which are described in the README#MacOS but then I used the one from the Build example and install all needed libs to a specific directory to use them with JUCE. Then I was able to see which libs I have to add.

I also had to add these linker flags:

```
-lcurl
-lbsm
```

Now I have to do the same for Windows, but I think this will be finished faster ;)
