### ISSUE TITLE
Support Windows on ARM64

### ISSUE THREAD

**Issue by ddula** [getsentry/sentry-native#588]
Windows can run on machines that are powered by ARM64 processors.

Does sentry-native have plans to support Windows on ARM64?

**Comment by Swatinem** [comment]
I think this should be supported, I don’t see a reason why not.
Though none of us engineers have such a machine to actually test this.

**Comment by cnicolaescu** [comment]
> Though none of us engineers have such a machine to actually test this.

One option is to cross-compile from a x86_64 device to ARM64 - at least for the build part.

Currently the following compilation error occurs when trying to compile for ARM64:
```
src\unwinder\sentry_unwinder_dbghelp.c(48): error C2039: 'Rip': is not a member of '_CONTEXT'

C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winnt.h(6549): note: see declaration of '_CONTEXT'
```

**Comment by Swatinem** [comment]
Cross compiling would indeed be an option for builds, but that still leaves the question of running tests. Preferably in CI, as otherwise things can break at any point.

We as a team are currently in a process to more clearly define what we want to actively support or *not*.

That said, Windows arm64 is not something we plan on actively supporting anytime soon, though we are always happy to receive contributions.
