### ISSUE TITLE
Performance Monitoring / Tracing integration with sentry-native

### ISSUE THREAD

**Issue by kunaljaydesai** [getsentry/sentry-native#601]
I noticed JS and Python SDK supports the Sentry Performance Monitoring / Tracing integration. Will sentry-native support this soon too?

**Comment by Swatinem** [comment]
We will be looking into it in the future, yes.

**Comment by MartinDelille** [comment]
I suppose it will be available in the next release ? Do you have a date ?

**Comment by flub** [comment]
> I suppose it will be available in the next release ? Do you have a date ?

currently expected to be released around end of Jan or earlyish Feb (as experimental api, but many parts of the native sdk are such).  but that's not an official promise :)

**Comment by parsley72** [comment]
It's been 8 months, any update?

**Comment by flub** [comment]
This has been released for a while (according to the changelog since 0.4.16 on 21 April), see https://github.com/getsentry/sentry-native/blob/5962300ea77bc546d293f15c7b091051a8abace6/include/sentry.h#L1415 for a starting point in the API.  From there you can add info to transactions, add child spans etc.

**Comment by parsley72** [comment]
The documentation for native on https://docs.sentry.io/platforms/native/performance/ still says:
> The platform or SDK you've selected either does not support this functionality, or it is missing from documentation.
