### ISSUE TITLE
valgrind shows memoryleak

### ISSUE THREAD

**Issue by AndreyMlashkin** [getsentry/sentry-native#609]
**Description**

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**
Ubuntu 20.04
GCC 10
cmake 3.18.4

- OS: [e.g. Windows 10, 64-bit]
- Compiler: [e.g. MSVC 19]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**
run an example program with valgrind

**Log output**
valgrind output is following:
344 bytes in 1 blocks are still reachable in loss record 3,108 of 3,397
  in Sentry::cleanup() in /home/andrei/sources/pictofitstudio/source/Utilities/Sentry.cpp:247
  1: malloc in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so
  2: sentry_malloc in /home/andrei/.conan/data/sentry-native/0.4.12/_/_/build/ce5930022ff459fe5ea29233688db781b249903f/source_subfolder/src/sentry_alloc.c:21
  3: sentry__envelope_new in /home/andrei/.conan/data/sentry-native/0.4.12/_/_/build/ce5930022ff459fe5ea29233688db781b249903f/source_subfolder/src/sentry_envelope.c:139
  4: sentry_end_session in /home/andrei/.conan/data/sentry-native/0.4.12/_/_/build/ce5930022ff459fe5ea29233688db781b249903f/source_subfolder/src/sentry_session.c:272
  5: sentry_close in /home/andrei/.conan/data/sentry-native/0.4.12/_/_/build/ce5930022ff459fe5ea29233688db781b249903f/source_subfolder/src/sentry_core.c:209
  6: Sentry::cleanup() in /home/andrei/sources/pictofitstudio/source/Utilities/Sentry.cpp:247
 ...
 9: main in /home/andrei/sources/pictofitstudio/source/pictofitmain.cpp:103

Looking to source code, the problem is clearly visible:
sentry_envelope_t *envelope = sentry__envelope_new();
this memory is never deleted

**Comment by Swatinem** [comment]
The envelope is passed to the `sentry__capture_envelope` function inside of `sentry_end_session`, which is responsible to free it.
I was thinking about the `SENTRY_WITH_OPTIONS` not being executed, however that case should never happen as otherwise you wouldn’t get a valid session from `sentry__end_session_internal` in the first place.

Are you using the default `curl` transport, or do you have some custom code there?

Also, does this happen at the time of a crash? I see you are on Ubuntu, and on that platform we intentionally leak memory once we hit our signal handler, as we are bypassing the system allocator.

**Comment by AndreyMlashkin** [comment]
It was an error on our side: we haven't called sentry_close in under sertain conditions

**Comment by Swatinem** [comment]
That is good to know, thanks for clarifying!
