### ISSUE TITLE
How to report only crash type

### ISSUE THREAD

**Issue by toby20130333** [getsentry/sentry-native#658]
Hi: 
 In Sentry platform,
 I found many error types reported.
 In fact, I only need crash type, and do not need other types of report
 C + + platform:
     What can I do to solve this problem?
    I didn't find any interface in Sentry-native

**Comment by flub** [comment]
Hi, if you follow the documentation at https://docs.sentry.io/platforms/native/ it will guide you how to setup the sdk.  By default it will only capture crashes using the backend configured so unless you manually capture other errors that is how the sdk behaves I think.

**Comment by toby20130333** [comment]
![image](https://user-images.githubusercontent.com/4186642/149773954-eb8ba9a5-87b0-46ca-985c-3a9524c5b487.png)
Hello,this error or crashed is not my project code,It's Qt SDK or win api error
So what can i do ?

**Comment by toby20130333** [comment]
![image](https://user-images.githubusercontent.com/4186642/149774227-b02112e2-c99b-474c-be7e-d27d606c4317.png)
I use sentry code by default
 : sentry sdk init

**Comment by toby20130333** [comment]
abnormal stauts as a crashed?

**Comment by flub** [comment]
From what I can tell in the screenshot (it is partially obscured) this is still a hard crash from your application, quite possibly still caused by your app unless QT has some unresolved hard crashes.

If you really don't want those crashes your simples option is to use the "ignore" functionality in the UI.  Otherwise, depending on the backend you use with sentry-native you might be able to filter events on the client side, see https://docs.sentry.io/platforms/native/configuration/filtering/
