### ISSUE TITLE
Sentry-native "Capturing Events" encountered 2 error show up from sentry server

### ISSUE THREAD

**Issue by austinlin7732** [getsentry/sentry-native#68]
[Refer to Capturing Events in Sentry Doc](https://docs.sentry.io/error-reporting/capturing/?platform=native#capturing-errors--exceptions), I send the event to sentry server, and I see 2 error while processing this event.     

![image](https://user-images.githubusercontent.com/50258355/66818622-2bb26d00-ef70-11e9-86c6-8331b07a2c84.png)

**The capture event in sentry server:**  
![image](https://user-images.githubusercontent.com/50258355/66818977-bdba7580-ef70-11e9-85e3-6d5ac01aba37.png)

**My example code follow the sentry Doc,**  
![image](https://user-images.githubusercontent.com/50258355/66818721-56042a80-ef70-11e9-8ed2-027986402fe8.png)  
No error happened but event still sent out because of using `sentry_capture_event`

Q1,  why does `debug_meta.images.0.debug_id` and `debug_meta.images.2.debug_id` said it `Missing value for required attribute`?  
Do I need to set up anything with sentry option in source code? 

**[Check the usage for capture event]**
Q2: After some testing, the exception event looks not going to catch the error automatically, we need to catch every condition manually to sent the event like my thought below right?

**[My thought]**
```
sentry_value_t exc = sentry_value_new_object();
sentry_value_set_by_key(exc, "type", sentry_value_new_string("Exception TESTING"));
sentry_value_set_by_key(exc, "value", sentry_value_new_string("Error message TESTING."));

if ( SUCCEED)
{
   return 0;
}else{
   sentry_value_set_by_key(event, "exception", exc);
    sentry_capture_event(event);
}
```

**Comment by Swatinem** [comment]
@austinlin7732 

Q1:
You have to make sure to generate your lib/exe with the `--build-id` linker flag so that it gets a proper `debug_id`. We plan to eventually implement a fallback, although its not high priority right now.

Q2:
I don’t really understand your question? `sentry-native` does not do any `catch` at all. You can manually send events that confirm to the `exception` payload (https://docs.sentry.io/development/sdk-dev/event-payloads/exception/) according to your application logic.
