### ISSUE TITLE
Investigate Native SDK Backend/Session behaviour on Shutdown on M1

### ISSUE THREAD

**Issue by ashwoods** [getsentry/sentry-native#716]
We would want to verify how the Native SDK behaves in these instances:

Various ways of process termination:

- KILL / TERM
- Logout / Shutdown

Using the following backends:

- crashpad
- breakpad

All that, specifically on macOS on the M1.

STR:

Possibly patch up the native example, increasing this sleep here: https://github.com/getsentry/sentry-native/blob/bd56100922e1359c08f512e84ab975972788dc98/examples/example.c#L177

Then build the example with the various backends, and start it like so:
`sentry_example log start-session sleep`.
… and then kill it in various ways.
Observe if a crash report and which kind of session status is being reported.

**Comment by supervacuus** [comment]
I can do the testing and create further issues if I see any unwanted behavior.

**Comment by Swatinem** [comment]
The specific case we would like to confirm in our testing, which came from a customer:
They report that with **crashpad**, when the process is forcibly killed on shutdown due to taking too long to terminate, they observe a crash log, which in turn flags the session as `crashed` due to filesystem timestamps.

Not quite sure this will necessarily exhibit that case, maybe you would have to install a handler for SIGTERM or whatever is signalling the process to pls shut down; and then run into a timeout there.

The desired outcome here would be: don’t create a `crashed` session if the process is being forcibly killed on shutdown, but rather a `abnormal` session.

**Comment by supervacuus** [comment]
@ashwoods, @Swatinem, since this was coming from support: was this ever raised again? I would like to close this otherwise.

**Comment by ashwoods** [comment]
Hasn't resurfaced since, closing now.
