### ISSUE TITLE
dmp file is not created on mac with sdk 0.4.18 Latest

### ISSUE THREAD

**Issue by RabindraUBA** [getsentry/sentry-native#733]
Hi,

I have used  0.4.18 latest SDK, I am able to compile and generate the necessary library for MacOSX and windows version. 
When I tested for crash report in both mac and windows, only windows is working as expected and reporting the .dmp file to my sentry dsn.
But I am getting issue on mac version that, not able to get .dmp file created on my sentry-native db folder and sentry dsn as well.

these are my compilation steps:
1. cmake -B build -D SENTRY_BACKEND=crashpad
2. cmake --build build  --parallel 
3. cmake --install build --prefix install
4. exa --tree install --level 2

**code Initialization**
  sentry_options_t* opt = sentry_options_new();
  sentry_options_set_dsn(opt,"my_dsn_Url");
  sentry_options_set_database_path(opt, "sentry-native);
  sentry_init(opt);
  trigger_crash();
 sentry_close();

//crash code
trigger_crash()
{
    memset((char *)invalid_mem, 1, 100);
}

Sentry-native folder is created on database_path with following structure:

1. attachments (Folder)
2. b8bdeb42-e82d-4f17-355c-c702c87b8198.run (Folder

> _sentry-breadcrumb1
> _sentry-breadcrumb2
>_sentry-event

3. b8bdeb42-e82d-4f17-355c-c702c87b8198.run.lock (file
4. completed (folder)
5. new (folder)
6. pending (folder)
7. settings.dat (file)

Please suggest me..  am I missing any steps in mac configuration?

**Comment by supervacuus** [comment]
Hi! Can I ask you to run your program with the debug-printing mode enabled?

Just add `sentry_options_set_debug(options, 1);` right before your `sentry_init` invocation. Can you see any errors (besides the intentional crash)?

You can also run the example program to verify that the crashpad_handler works in your environment. From within your CMake build directory:

`./sentry_example log crash no-setup`

**Comment by RabindraUBA** [comment]
[sentry] INFO using database path "/Users/abc/Desktop/sentrydemo/sentry-native"
[sentry] DEBUG starting transport
[sentry] DEBUG starting background worker thread
[sentry] DEBUG starting backend
[sentry] DEBUG background worker thread started
[sentry] DEBUG starting crashpad backend with handler "/Users/abc/Library/Developer/Xcode/DerivedData/sentrydemo-dmkjbgkydjtembekbjybdkdlwxrn/Build/Products/Debug/crashpad_handler"
[sentry] DEBUG using minidump url "https://oxxxxxxxx.ingest.sentry.io:443/api/1xxxxxxx/minidump/?sentry_client=sentry.native/0.4.18&sentry_key=xxxxxxxxxxxxxxxxxxxxx"
[sentry] INFO started crashpad client handler
[sentry] DEBUG processing and pruning old runs
zsh: segmentation fault  

Note: zsh: segmentation fault this is only showing while triggering crash code.


otherwise, it will show following

[sentry] DEBUG shutting down backend
[sentry] DEBUG shutting down transport
[sentry] DEBUG shutting down background worker thread
[sentry] DEBUG submitting task to background worker thread
[sentry] DEBUG executing task on worker thread
[sentry] DEBUG background worker thread shut down

**Comment by supervacuus** [comment]
This looks fine. It is expected that there are no other logs after the crash because there is no interaction between the crashpad handler and the application on macOS after a crash (this is a current limitation of crashpad on macOS). 

This means that the `before_send()` hook will not be invoked (and a couple of other session maintenance/termination steps). It also means that the database directory structure will look slightly different between Windows and macOS after a crash. Nevertheless, crashpad should produce a dump file in either the `completed` or `pending` folders; this is entirely independent of our SDK. The SDK will pick up the macOS crashes on the next application start.

Do you build crashpad from our release package or provide an independent crashpad build?

**Comment by RabindraUBA** [comment]
Crashpad was generated by following command in release package
cmake -B build -D SENTRY_BACKEND=crashpad
cmake --build build --parallel
cmake --install build --prefix install
exa --tree install --level 2

**Comment by supervacuus** [comment]
Understood, I only asked because the crashpad handler path in your log-output points to a directory that is not in the build-output of the described build. You probably just copied it to another directory. This might be irrelevant, but I must make sure that your environment is similar to our repro setup.

I will have to get back to you with further questions tomorrow.

**Comment by supervacuus** [comment]
Sentry does have a CI system that tests this setup with every change, but I now also tested this manually on 3 different macs just to make sure our testing is not biased to the particular CI setup. I tested on macs with different CPU architectures and macOS versions ranging from 10.15 to 12.4, all machines in different states of maintenance :-). This is my basic test sequence:

```bash
# download the release package with all dependencies
wget https://github.com/getsentry/sentry-native/releases/download/0.4.18/sentry-native.zip
# extract the source
unzip sentry-native.zip -d sentry-native
# use the default build-generator for macOS including the default crashpad backend
cmake -B sentry-native/build -S sentry-native
# build the whole project
cmake --build sentry-native/build --parallel
# make sure the crashpad_handler is colocated with the example since it expects it there
cp sentry-native/build/crashpad_build/handler/crashpad_handler sentry-native/build
# invoke the example, pass the DSN via env and command to log and crash
SENTRY_DSN=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxx.ingest.sentry.io/xxxxxxx ./sentry-native/build/sentry_example log crash
# tree-view of the database path
exa --tree .sentry-native
```

I was not able to reproduce the issue on any setup i.e. all database path trees revealed a dump file either in either the `pending` or `completed` subfolder like this:

```
.sentry-native
├── attachments
│  └── 720b098b-01b5-4164-92de-88aa1c55e074
│     ├── __sentry-breadcrumb1
│     ├── __sentry-breadcrumb2
│     └── __sentry-event
├── completed
├── d2dc0846-412d-4080-535f-c87be01c5159.run
│  ├── __sentry-breadcrumb1
│  ├── __sentry-breadcrumb2
│  └── __sentry-event
├── d2dc0846-412d-4080-535f-c87be01c5159.run.lock
├── new
├── pending
│  └── 720b098b-01b5-4164-92de-88aa1c55e074.dmp
└── settings.dat
```

Can I ask you to try this so we have a reproducible setup?

**Comment by RabindraUBA** [comment]
resolved, thanks
