### ISSUE TITLE
[Default Environment] Minidumps do not inherit a default environment

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-native#737]
No [default environment](https://github.com/getsentry/develop/pull/656) is assigned for minidumps when using the sentry-native SDK. This can cause problems when using releases.

When an [environment is not set](https://docs.sentry.io/platforms/native/configuration/options/#environment) minidumps will not be assigned a default environment.

- [ ] During build
- [ ] During run-time
- [x] When capturing a hard crash

**Environment**

- Windows 10, 64-bit

**Comment by supervacuus** [comment]
Thanks, @souredoutlook. I will take care of this.

**Comment by supervacuus** [comment]
The linked doc entry https://docs.sentry.io/platforms/native/configuration/options/#environment is defined in the [common section of the documentation](https://github.com/getsentry/sentry-docs/blob/master/src/platforms/common/configuration/options.mdx?plain=1#L100-L106) (i.e., the same for all SDK platforms).

Maybe there should be a linked issue in `sentry-docs` too?

**Comment by souredoutlook** [comment]
@supervacuus that's a good point - this SDK likely needs a [platform-specific page](https://docs.sentry.io/platforms/ruby/configuration/options/) similar to the linked Ruby options. I'll open an issue there as well.

**Comment by supervacuus** [comment]
@souredoutlook Thank you for your reply, but I am not sure I follow; please bear with me:

I understand that this behavior (environment defaults to `production` if not overwritten via the environment) should be followed by _all_ SDK platforms that can comply (at least, that is the implication for me from the changes to the developer docs). Is this correct, or is only _sentry-native_ affected by this (because we are the only ones who do not default to `production`)?

If all SDK platforms need to comply, my suggestion from above is to change the common section for _all platforms_ and not to establish a platform-specific page for _sentry-native_. At least, after all SDK platforms have been validated to conform to the expected behavior.

The linked PR (#739) changes the behavior as defined here: https://github.com/getsentry/develop/pull/656, but we probably should not merge it before the docs are adapted.

Or are you suggesting we create a sentry-native-specific attribute configuration until all other platform SDKs comply (I have no idea how many of them default to `production`, but as the docs suggest, most probably shouldn't)?

**Comment by souredoutlook** [comment]
@supervacuus - my apologies I misunderstood your initial point.

- Yes I agree we should document this default behaviour outside of the developer docs.
- I also believe it is worth reviewing the configuration options on [the linked docs page](https://docs.sentry.io/platforms/native/configuration/options/#environment) as those docs don't actually detail how to set the environment in sentry-native.

**Comment by supervacuus** [comment]
What we can do is similar to what unity and .net currently do:

* they [remove themselves from the common text](https://github.com/getsentry/sentry-docs/blob/master/src/platforms/common/configuration/options.mdx?plain=1#L100-L106) via `notSupported` 
* and then [add their platform-specific text right below](https://github.com/getsentry/sentry-docs/blob/master/src/platforms/common/configuration/options.mdx?plain=1#L114-L130) via `supported`

Our text is probably going to be 1:1 with the unity one. I can create a PR for this if that makes sense.

**Comment by supervacuus** [comment]
haha, sorry... https://github.com/getsentry/sentry-docs/issues/5358#issuecomment-1198328515

so, it seems that is indeed the preferred option.
