### ISSUE TITLE
Building with 32 bit flag on linux does not properly set curl libary to 32 bit

### ISSUE THREAD

**Issue by sapphonie** [getsentry/sentry-native#760]
**Description**

Building with 32 bit flag on linux does not properly use the 32 curl library.

**When does the problem happen**

When building sentry native

**Environment**

Debian 11, happens regardless of Clang/GCC

**Steps To Reproduce**

```
sudo apt install libcurl4-gnutls-dev libcurl4-gnutls-dev:i386
cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSENTRY_BUILD_FORCE32=yes
cmake --build build --parallel
```

**Log output**

```
[ 98%] Linking CXX executable sentry_test_unit
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [tests/unit/CMakeFiles/sentry_test_unit.dir/build.make:990: tests/unit/sentry_test_unit] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:269: tests/unit/CMakeFiles/sentry_test_unit.dir/all] Error 2
[ 98%] Linking CXX shared library libsentry.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/sentry.dir/build.make:615: libsentry.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/sentry.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2
```

Probably fixable by doing something like
```
SET(CMAKE_LIBRARY_PATH "/usr/lib/i386-linux-gnu")
include_directories(BEFORE /usr/include/i386-linux-gnu)
```
if building 32 bit? That is what worked for me, but I doubt it's portable

**Comment by supervacuus** [comment]
Hi @sapphonie. Yes, `find_package`/`find_library` in `CMake` and `pkg-config` require a lookup path if you want to build an architecture that is not the host's default. You are effectively doing a cross-compilation, and `sentry-native` only handles the portable part since there is little standardization across distros concerning the naming of non-host library paths. And for the same reason, we will not include hard-coded per-distro paths in the library configuration.

Ideally, `i386` and `amd64` should be separated into sysroots, as would be the case when building for ARM on a non-ARM host. For x86, many package managers provide the convenience of allowing us to install in the same sysroot as a multi-arch setup, but this doesn't obsolete the need to specify the non-host library and include paths on most distros.

If this is a reoccurring situation for you with multiple distributions (and therefore different paths), I recommend preparing a set of toolchain files for CMake. But in your case, you are served equally well with this CMake invocation:

```
cmake -B build \
    -DSENTRY_BUILD_FORCE32=yes \
    -DCMAKE_LIBRARY_PATH=/usr/lib/i386-linux-gnu \
    -DCMAKE_INCLUDE_PATH=/usr/include/i386-linux-gnu
```

Because we are not explicitly adding any system paths ourselves in `sentry-native`, you and any other user can overwrite the host defaults without conflicts.

**Comment by sapphonie** [comment]
Hey thanks, I'm not the most familiar with CMake, this is definitely cleaner than editing the CMakeLists file, lol. Closing this
