### ISSUE TITLE
can't build with msys2

### ISSUE THREAD

**Issue by mariuszmaximus** [getsentry/sentry-native#769]
**Description**
build on msys2 platform: minidump_thread_name_list_writer.h:147:3: error: unknown type name 'MINIDUMP_THREAD_NAME_LIST'

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10, 64-bit
- Compiler: Clang 15.0.0 MSYS2 
- CMake version and config: cmake-3.24.1-windows-x86_64

**Steps To Reproduce**

```
$ pacman -S --needed - < ./toolchains/msys2-mingw64-pkglist.txt
$ export MINGW_ROOT=/c/msys64/mingw64
$ cmake -GNinja -Bbuild -H. -DCMAKE_TOOLCHAIN_FILE=toolchains/msys2.cmake 
$ ninja -C build
```

**Log output**
(https://pastebin.com/8jSzb9tU)

**Comment by Swatinem** [comment]
This was raised already somewhere, though I can’t seem to find the ticket.

The problem here is upstream, as msys2 / mingw do not provide up-to-date headers. The Windows SDK does have these definitions since some version, though those definitions are not documented on the Web. :-(

Other than this, the msys2 / mingw support is community supported, so we do appreciate PRs to fix these issues, but we will not actively support these things ourselves. But as I said, this rather needs a fix upstream to put these definitions into the upstream headers.

**Comment by mariuszmaximus** [comment]
I temporary fix msys2 includes 
I confirm, build is possible
$ ./sentry_test_unit.exe
FAILED: 25 of 96 unit tests have failed.

https://pastebin.com/NFWjX15G

**Comment by Swatinem** [comment]
Your pastebin link seems to be private. I would be curious to see what the failures are?

**Comment by mariuszmaximus** [comment]
Pastebin’s SMART filters have detected potentially offensive or questionable content in your Paste
... This Paste can only be published with the visibility set to "Private".  :( 

please look at gist.github version:
https://gist.github.com/mariuszmaximus/f834434b7d26e11c507af757d9245a79

**Comment by mariuszmaximus** [comment]
SUCCESS: All unit tests have passed.

**Comment by mariuszmaximus** [comment]
I start debug for sentry_test_unit.exe 
sentry_test_unit need crashpad_handler.exe in folder  but it was build in different directory
I'll make a fork and send a push

**Comment by Swatinem** [comment]
I believe the unit tests are all built without any crash backend. the backend is tested with the integration test suite instead.
