### ISSUE TITLE
uninitialized variable

### ISSUE THREAD

**Issue by maddin200** [getsentry/sentry-native#814]
sentry-native-master/src/path/sentry_path_unix.c line 303
Code:
int
sentry__path_remove(const sentry_path_t *path)
{
    int status;  // <- maybe better status = 0;
    if (!sentry__path_is_dir(path)) {
        EINTR_RETRY(unlink(path->path), &status);
        if (status == 0) {
            return 0;
        }

**Comment by supervacuus** [comment]
Thanks, @maddin200, for the hint! It might not be obvious, but `status` is an output variable to `EINTR_RETRY`. It only needs to have a non-null address (which is satisfied) since the macro expands to:

```C
do {
    int _tmp;
    do {
        _tmp = (unlink(path->path));
    } while (_tmp == -1 && (*__error()) == EINTR);
    if (&status != 0) {
        *(int *)&status = _tmp;
    }
} while (false)
```

Since the remaining code also leaves output variables uninitialized, I would leave the declaration as it is, as this consistently signals their use to other developers.
