### ISSUE TITLE
sentry_init() takes too much time and blocks UI thread

### ISSUE THREAD

**Issue by nenseso** [getsentry/sentry-native#896]
**Description**
Using sentry-native version 0.6.1, I tested the project startup speed and found that it took a very long time, 2.9s. I checked it through instruments-App Launch and found that the function stack is as follows. Is there any way to optimize it?
![image](https://github.com/getsentry/sentry-native/assets/16931967/db2be202-808f-45ad-8156-5f8e2634a45c)
![image](https://github.com/getsentry/sentry-native/assets/16931967/08514bca-f6fa-4ad9-beb1-94dfab4067e9)

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. macOS 13.5.2, Apple M1]
- Compiler: [AppleClang 14.0.3.14030022]
- CMake version and config: [3.24.2]

**Comment by supervacuus** [comment]
Hello @nenseso, and thanks for the report! Can you provide more context on your setup? I would be surprised if, in a release build of the Native SDK, `sentry_init()` with the crashpad-backend on macOS would take more than a couple of milliseconds to initialize (the Native SDK is also developed on M1-based macOS systems, so that would immediately be apparent). This must be an issue that is connected with your environment.

It also seems from your first screenshot that it is not the `ChildPortHandshake::RunClient()` path that is responsible for the significant delay, but rather the code (where the symbol couldn't be resolved) that executes in `HandlerStarter::CommonStart()` before that. Before the handshake, the `crashpad_handler` is started. Do you have a virus scanner or any (security-related) background process that monitors application starts?

**Comment by nenseso** [comment]
Thank you for your reply! I re-tested many times and found that instruments-App Launch seems to affect the execution time of senty_init()
Testing Method:
1. Add execution time test code before and after sentry_init()
```
    auto start = std::chrono::high_resolution_clock::now();

    sentry_init(options);
    
    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
    LOGI("sentry init duration: {} microseconds", duration);
```
2. After building the debug product package on the local machine, use instruments-App Launch or manually click to launch the application. Sentry starts very quickly, about a few hundred µs, as shown in the figure. (Native environment: Apple M1, macOS 13.5. 2)
![image-20231020101530519](https://github.com/getsentry/sentry-native/assets/16931967/7041ec3b-bdf4-445b-b3e6-922861ab7d0f)
3. After building the release product package on the build machine, use instruments-App Launch to launch the application. Sometimes the time can reach an astonishing 14.5 seconds! (Build machine environment: Apple M2 macOS 13.5.2), the address here cannot be resolved, although I have symbolized it
![image-20231020103057857](https://github.com/getsentry/sentry-native/assets/16931967/5d525025-0976-4727-903a-65e5ab245712)

This is the result of my repeated testing using App Launch many times
<!DOCTYPE html><figure class="md-table-fig" cid="n92" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">

Weight | Self Weight | Symbol Name
-- | -- | --
14.50 s    76.5% | 0 s | sentry_init
11.15 s     69.7% | 0 s | sentry_init
8.06 s     69.1% | 0 s | sentry_init
3.00 s     4.0% | 0 s | sentry_init
2.34 s     29.9% | 0 s | sentry_init
2.26 s     3.8% | 0 s | sentry_init

</figure>

4. Manually click to pull up the build machine to build the release product package. The startup speed of sentry is normal, as shown in the log.
_sentry init duration: 1602 microseconds
sentry init duration: 989 microseconds
sentry init duration: 367 microseconds
sentry init duration: 356 microseconds
sentry init duration: 332 microseconds
sentry init duration: 342 microseconds
sentry init duration: 342 microseconds_

Through the above tests, I think this should not affect the normal startup speed of online users, but it is not clear why instruments-App Launch causes this result.

**Comment by supervacuus** [comment]
Thanks for the investigation @nenseso. Good to hear that `sentry_init()` doesn't go beyond a couple of milliseconds outside the profiler.

> After building the debug product package on the local machine, use instruments-App Launch or manually click to launch the application. Sentry starts very quickly, about a few hundred µs, as shown in the figure. (Native environment: Apple M1, macOS 13.5. 2)

That means the profiler produces similar numbers for the debug build to when you instrument your code manually. That is also great news.

> After building the release product package on the build machine, use instruments-App Launch to launch the application. Sometimes the time can reach an astonishing 14.5 seconds! (Build machine environment: Apple M2 macOS 13.5.2), the address here cannot be resolved, although I have symbolized it

That you do not get a symbol typically means that the compiler inlined and optimized one or more functions for the release build. Counter to intuition, that could also be why the profiler has issues with the code, possibly incorrectly sampling the execution but also interfering with highly optimized code. 

This part of the code deals with bootstrapping the mach-port IPC between the client and the handler and I could imagine that a sampling profiler could introduce delays to not affect the correct execution of these calls. But these are just mere guesses since I have no insight into how the Instruments profiler works.

**Comment by nenseso** [comment]
Thanks @supervacuus

**Comment by supervacuus** [comment]
You're welcome @nenseso. We are always interested in performance issues.
