### ISSUE TITLE
Static build with breakpad on windows fails to link

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-native#909]
**Description**

I'm building sentry-native statically with the breakpad backend. During the final app linking phase, there's a bunch of errors like:

`Runtime.WorkstationGC.lib(EHHelpers.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in sentry-native.lib(sentry_backend_breakpad.obj) [C:\dev\dotnet\integration-test\console-app\console-app.csproj]`

Looks like we're not passing some build config down to the breakpad build.

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

```
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- SENTRY_TRANSPORT=winhttp
-- SENTRY_BACKEND=breakpad
-- SENTRY_LIBRARY_TYPE=STATIC
-- SENTRY_SDK_NAME=sentry.native.dotnet
-- Configuring done (0.1s)
```

**Steps To Reproduce**

I don't have a native-only repro at hand, this is done as part of the sentry-dotnet SDK integration in https://github.com/getsentry/sentry-dotnet/pull/2887

**Comment by supervacuus** [comment]
> `Runtime.WorkstationGC.lib(EHHelpers.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in sentry-native.lib(sentry_backend_breakpad.obj) [C:\dev\dotnet\integration-test\console-app\console-app.csproj]`

This means that you need to align the type of runtime library you configure for both projects because they have to be the same:

* `MT` vs. `MD`: multi-threaded static vs. multi-threaded dynamic (the latter loads the "runtime" DLL during runtime)
* you can tell `sentry-native` which runtime library you want to use via `SENTRY_BUILD_RUNTIMESTATIC`
* the option between static or dynamic runtime library is orthogonal to `SENTRY_BUILD_SHARED_LIBS` which only affects the type of library `sentry-native` should be (i.e. you can have a static native library that loads the runtime dynamically).

**Comment by vaind** [comment]
Thanks @supervacuus, I'll check the configs once more. 

Just to clarify, this is only an issue with the breakpad backend (`SENTRY_BACKEND=breakpad`), all other backends compile just fine (on Windows) with the rest of the configuration being the same.

**Comment by supervacuus** [comment]
The cmake invocation you suggested here, https://github.com/getsentry/sentry-native/issues/895, will use a static runtime.

In the configuration here, https://github.com/getsentry/sentry-dotnet/blob/2e51a9f9c028c9c37119715310143f788a035876/scripts/build-sentry-native.ps1#L46, it will be loading the runtime dynamically.

**Comment by supervacuus** [comment]
> Just to clarify, this is only an issue with the breakpad backend (`SENTRY_BACKEND=breakpad`), all other backends compile just fine (on Windows) with the rest of the configuration being the same.

This would be surprising with `crashpad`. With `inproc` being essentially a couple of C functions and not a single line of C++, there is no need for a lot of runtime support, I could imagine that it only depends on `libcmt.lib`, which is static anyway and there is no collision because it doesn't depend on any `MSVCRT`.
