### ISSUE TITLE
[c++]Sentry Unable to report Crashes when running as Daemon/systemd service

### ISSUE THREAD

**Issue by aholster** [getsentry/sentry-native#921]
**Description**

Sentry is unable to send crash reports when the executable starting it was started as a systemd Daemon/service
Normal behaviour when executable is invoked normally.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Environment**

- OS: Ubuntu 22.04.3 LTS, ran in a WSL on win 10 pro Version	10.0.19045 Build 19045
- Compiler: Ubuntu clang version 17.0.0 (++20230822063031+1991da9a837d-1~exp1~20230822063143.27), x86_64-pc-linux-gnu
- CMake version and config: cmake version 3.22.1, config not sure, think just '-DCMAKE_BUILD_TYPE=RelWithDebInfo'?

Have not verified behaviour with other versions or environments at this time

**Steps To Reproduce**

(some variables in example are anonymized, indicated with <>)
1. Create basic c++ sentry application that crashes (used a null-dereference)

```
#include <sentry.h>

int main(int argc, char *argv[]) {

	sentry_options_t *options = sentry_options_new();
	sentry_options_set_dsn(options, <dsn>);
	sentry_options_set_release(options, <projname>);
	sentry_init(options);

	int *ptr = NULL;
	ptr[0] = 12;

	sentry_shutdown();
	return 0;
}
```
2. Write a basic systemd .service specification for your application and put it in the appropriate directory (/etc/systemd/system/)
eg:
```[Unit]
Description=Temporary Sentry Test Daemon

[Service]
WorkingDirectory=/home/<path>/build/debug/
ExecStart=/home/<path>/build/debug/sentry-test
TimeoutStopSec=5min
Restart=no
Type=exec

[Install]
WantedBy=multi-user.target
```
3. Run the service via `systemctl start <service name>`

**Log output**
N/a

**Comment by supervacuus** [comment]
Thanks for the report, @aholster. I will look into this; I am unaware of any restrictions when executing your application as a `systemd` service.

To be clear, when you use the default configuration on Linux, you are using the `breakpad` backend. The `breakpad` backend will persist the crash to disk and upload it with the next start. If you crash too early (which is likely in your example, where it happens right after `sentry_init()`), then the upload thread will not have enough time to send before the application is terminated. Does the problem persist if you sleep a few seconds before you crash?

If that turns out to be the case and you want your crashes to be immediately sent instead, I recommend using the `crashpad` backend, which is documented here: https://docs.sentry.io/platforms/native/configuration/backends/crashpad/

**Comment by aholster** [comment]
Oh, I fixed the example by adding a sleep command (oddly enough, it was working before too), and the behaviour is unchanged.

Returning crashes immediately is critical for our use-case, as we plan to use it to report on user crashes, and depending on the application being started again is not feasible. 

However, I do believe when I built sentry-native with `Crashpad `as backend, if run the executable with -v it returns:
```
crashpad_handler (Crashpad) 0.8.0
Copyright 2018 The Crashpad Authors
```
Which seems to indicate it is indeed `Crashpad`

I will try to see if running the updated test on a Linux vm instead of WSL yields different results

**Comment by aholster** [comment]
It works on the VM, so it might be a weird limitation of WSl?

**Comment by supervacuus** [comment]
> It works on the VM, so it might be a weird limitation of WSL?

That might well be the case since `systemd` has been available for WSL for only a year now, and many of the more well-known `systemd` services still have known limitations in WSL.

**Comment by supervacuus** [comment]
@aholster, I had a quick debugging session to look at what is happening with the process. And the `crashpad_handler` seems to get a `SIGTERM` from `systemd` before it can create and send a report. This is expected behavior according to the `systemd` [docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html): since the `KillMode` defaults to `control-group`:

> all remaining processes in the control group of this unit will be killed on unit stop (for services: after the stop command is executed, as configured with ExecStop=)

This is also true when the main process of a unit shuts down on its own (for instance, because it crashed). If you are not starting any other processes in this unit, you could set `KillMode=process` in your service file, where the `crashpad_handler` would live long enough to report the crash and then shut down independently. I know this is not recommended as per the documentation, but that is precisely the behavior required for the `crashpad_handler` life cycle.

**Comment by aholster** [comment]
Thank you for the input, that makes sense and I've tested it in a few different ways.
However, the theory does not match my observations in practice, on WSL the systemd Daemon is still not successfully sending reports, not even with `KillMode=none`.
The other test cases (WSL non-daemon, Linux server, daemon&non-daemon) all managed to report back even with the flaws in the test setup (lacking the pause, wrong Killmode etc)

**Comment by supervacuus** [comment]
> on WSL the systemd Daemon is still not successfully sending reports, not even with `KillMode=none`.

If this works correctly, you should be seeing a message in the `systemd` journal that says something like

```
Unit process <pid> (crashpad_handle) remains running after unit stopped.
```

after the main process exited.

> The other test cases (WSL non-daemon, Linux server daemon&non-daemon) all managed to report back 

These test cases work because

* WSL non-daemon: no supervisor shuts down the `crashpad_handler`, so it can run as long as needed.
* Linux server daemon&non-daemon: explained here https://github.com/getsentry/sentry-native/issues/921#issuecomment-1854012096

> even with the flaws in the test setup (lacking the pause, wrong Killmode etc)

With "the pause", do you mean the suggested sleep from https://github.com/getsentry/sentry-native/issues/921#issuecomment-1849017837? This is only necessary for a test case if you use a backend that requires a restart to capture events (like `breakpad`), because the upload happens in a background thread and doesn't block `sentry_init()`.

**Comment by aholster** [comment]
> > on WSL the systemd Daemon is still not successfully sending reports, not even with `KillMode=none`.
> 
> If this works correctly, you should be seeing a message in the `systemd` journal that says something like
> 
> ```
> Unit process <pid> (crashpad_handle) remains running after unit stopped.
> ```
> 
> after the main process exited.
> 
> > The other test cases (WSL non-daemon, Linux server daemon&non-daemon) all managed to report back
> 
> These test cases work because
> 
>     * WSL non-daemon: no supervisor shuts down the `crashpad_handler`, so it can run as long as needed.
> 
>     * Linux server daemon&non-daemon: explained here [[c++]Sentry Unable to report Crashes when running as Daemon/systemd service #921 (comment)](https://github.com/getsentry/sentry-native/issues/921#issuecomment-1854012096)
> 
> 
> > even with the flaws in the test setup (lacking the pause, wrong Killmode etc)
> 
> With "the pause", do you mean the suggested sleep from [#921 (comment)](https://github.com/getsentry/sentry-native/issues/921#issuecomment-1849017837)? This is only necessary for a test case if you use a backend that requires a restart to capture events (like `breakpad`), because the upload happens in a background thread and doesn't block `sentry_init()`.

Thank you, the line about systemd journal gave me the last information needed to fix it, one of the fields in the .service file in my last few tests was malformed and causing issues.
I have it working now, and the whole experience was highly enlightening.

I will need to look into a solution for killing other spawned processes in the daemon now that systemd won't take of it, but I think this resolves this issue.
