### ISSUE TITLE
Trouble sending crash reports in AWS Lambda execution environment

### ISSUE THREAD

**Issue by andre-tebart** [getsentry/sentry-native#925]
Hi,

we are deploying a C++ library to an AWS Lambda environment via a custom container image. The library is then called via python ctypes from a python process. While sending events via sentry_capture_event works just fine we are having trouble getting crash reports to work.

**Using the breakpad backend**
When using the breakpad backend and a crash occurs we get the following debug output from sentry:
```
[sentry] DEBUG starting transport
[sentry] DEBUG starting background worker thread
[sentry] DEBUG starting backend
[sentry] DEBUG background worker thread started
[sentry] WARN failed to set background worker thread name
[sentry] DEBUG processing and pruning old runs
[sentry] INFO entering breakpad minidump callback
[sentry] DEBUG merging scope into event
[sentry] DEBUG trying to read modules from /proc/self/maps
[sentry] DEBUG read 78 modules from /proc/self/maps
[sentry] DEBUG adding attachments to envelope
[sentry] WARN failed to read envelope item from "/tmp/.sentry-native/52faa445-0da9-4f99-efb1-b22dd6ad2b03.run/76e2e34c-7528-423a-b31cae90-e468fd89.dmp"
[sentry] DEBUG sending envelope
[sentry] DEBUG serializing envelope into buffer
[sentry] INFO crash has been captured
/lambda-entrypoint: line 3: 25 Aborted (core dumped) python3.11 -m awslambdaric $@
```

After the crash of the python process we start another python process to just initialize and teardown sentry and send out any pending crash reports:
```
[sentry] DEBUG starting transport
[sentry] DEBUG starting background worker thread
[sentry] DEBUG starting backend
[sentry] DEBUG processing and pruning old runs
[sentry] DEBUG background worker thread started
[sentry] WARN failed to set background worker thread name
[sentry] DEBUG sending envelope
[sentry] DEBUG submitting task to background worker thread
[sentry] DEBUG executing task on worker thread
* processing: https://o1367834.ingest.sentry.io:443/api/4505787457339392/envelope/
Flushing errors
Flushing done
*   Trying 34.120.195.249:443...
* Connected to o1367834.ingest.sentry.io (34.120.195.249) port 443
* ALPN: offers http/1.1
[sentry] INFO entering breakpad minidump callback
[sentry] DEBUG merging scope into event
[sentry] DEBUG trying to read modules from /proc/self/maps
[sentry] DEBUG read 61 modules from /proc/self/maps
[sentry] DEBUG adding attachments to envelope
[sentry] WARN failed to read envelope item from "/tmp/.sentry-native/4ff13b7d-4eff-4e54-09cb-264ac4382ab5.run/45ae39bf-26fe-4b4e-e77f6fa7-772af3af.dmp"
[sentry] DEBUG sending envelope
[sentry] DEBUG serializing envelope into buffer
[sentry] DEBUG dumped 1 in-flight envelopes to disk
[sentry] INFO crash has been captured
[sentry] DEBUG shutting down backend
[sentry] DEBUG shutting down transport
[sentry] DEBUG shutting down background worker thread
[sentry] DEBUG submitting task to background worker thread
/lambda-entrypoint: line 8:    37 Segmentation fault      (core dumped) python3.11 flush_errors.py
```
It looks like when trying to send the crash report it runs into another crash.

**Using the crashpad backend**
We also trie the crashpad handler with the following result:
```
[sentry] INFO using database path "/tmp/.sentry-native"
[sentry] DEBUG starting transport
[sentry] DEBUG starting background worker thread
[sentry] DEBUG starting backend
[sentry] DEBUG starting crashpad backend with handler "/usr/local/bin/crashpad_handler"
[sentry] DEBUG background worker thread started
[sentry] WARN failed to set background worker thread name
[sentry] DEBUG using minidump URL "https://o1367834.ingest.sentry.io:443/..."
[26:26:20231212,074412.618658:WARNING crashpad_client_linux.cc:376] prctl: Operation not permitted (1)
[sentry] INFO started crashpad client handler
[sentry] DEBUG processing and pruning old runs
[sentry] INFO flushing session and queue before crashpad handler
[sentry] INFO handing control over to crashpad
[30:30:20231212,074414.396741:ERROR scoped_ptrace_attach.cc:27] ptrace: Operation not permitted (1)
/lambda-entrypoint: line 3:    26 Aborted                 (core dumped) python3.11 -m awslambdaric $@
```

After that it show that the crashpad handler process is still running but in a defunct state:
```
crashpad_handle <defunct>
```

To my understanding the AWS Lambda execution environment does not allow certain system calls via Seccomp BPF which might explain the issues. Are there any workarounds to get at least some form of error reporting on crashes?

**Comment by supervacuus** [comment]
Hi @andre-tebart. Yes, AWS Lambda disables `ptrace` completely. Since both `breakpad` and `crashpad` require `ptrace` to produce a minidump, these backends will fail on Lambda. The only workaround I can suggest is to use the `inproc` backend, which does not generate a minidump from an external process and will only provide a stack trace of the crashed thread + the memory map required for symbolication.

**Comment by andre-tebart** [comment]
Thanks for the quick response. We will have a look at the inproc backend then.

**Comment by supervacuus** [comment]
Hi @andre-tebart,

I doubt we will have the time to investigate this issue. We currently do not support (or test) AWS Lambda, and from the logs, the issue is between the certificate store in your docker container and the TLS backend of your curl version (all asterisk prefixed logs come from `libcurl`).

If I were you, I would investigate the following:

* we sometimes had issues when another dependency in a client application was already linked with (often statically) or loaded another (incompatible) version of `libcurl` or `OpenSSL` because these have quite a few globals that might conflict. If that is the case, then you must choose which to load.
* whether the default certificate store path is correct (you can set alternative paths with the SDK API: https://github.com/getsentry/sentry-native/blob/master/include/sentry.h#L982-L989)
* whether the certificate file has been corrupted or access to it is somehow affected when running your container on the AWS lambda VM. In your initial issue, when using breakpad, you also crashed during the next run at the same spot, during or after the application-layer protocol negotiation, so that issue seems to be consistent with the transport and independent of the crash backend
* find a way to retrieve the crash recorded by the `inproc` backend (which you will find in `/tmp/.sentry-native` of that AWS lambda instance) because that should better indicate the problem's source.
* try `libcurl` with another TLS backend in your container image

**Comment by supervacuus** [comment]
cc: @kahest
