### ISSUE TITLE
API function to check if there are crashes to report

### ISSUE THREAD

**Issue by dacap** [getsentry/sentry-native#930]
It probably already exists but I didn't find it, it would be nice to have an function to check if there are any crash to report, so we can ask/show a checkbox for consent to share crash reports to the user only when there are crashes.

E.g. we show to the user the consent checkbox only when we find a crash in the Sentry folder, using [this](https://github.com/aseprite/aseprite/blob/88e89b6c3807e350154ec71742712fef445a29e1/src/app/sentry_wrapper.cpp#L95-L120), which basically checks if there is a `last_crash` file, or `.dmp` file in `completed`/`reports` subdirs, inside the Sentry DB directory.

Probably there is an easier way to do this.

**Comment by supervacuus** [comment]
Hi @dacap. We do provide an API to query whether there was a crash during the last run:

https://github.com/getsentry/sentry-native/blob/a3d58622a807b9dda174cb9fc18fa0f98c89d043/include/sentry.h#L1990-L2016

Is that what you are looking for? These together with the consent options functions:

https://github.com/getsentry/sentry-native/blob/a3d58622a807b9dda174cb9fc18fa0f98c89d043/include/sentry.h#L1093-L1107

and the consent API after `sentry_init()`

https://github.com/getsentry/sentry-native/blob/a3d58622a807b9dda174cb9fc18fa0f98c89d043/include/sentry.h#L1331-L1349

should be all you need for your use-case.

**Comment by dacap** [comment]
Hi @supervacuus, thanks for your answer, that's exactly what we are looking for (and as we don't use `sentry_clear_crashed_last_run()` calling `sentry_get_crashed_last_run()` we can check if the last run or any other run in the past have crashed).

Thanks 👍

**Comment by supervacuus** [comment]
@dacap, I just saw that you also use the native SDK on macOS. Sadly, with `crashpad`, we still have the problem that our crash handler in the SDK will not get called during a crash (while the crash will still get sent through the `crashpad_handler`).

That means your workaround for macOS should stay in the code because the `last_crash` marker will not get created and that approach is valid in your case since you do not use `sentry_clear_crashed_last_run()`

**Comment by dacap** [comment]
> That means your workaround for macOS should stay in the code

Thanks for the comment @supervacuus, I'll revert the change keeping it for macOS only. Is there a plan to fix this in the future? (I guess that just having a flag file like the `user-consent` one might help for all platforms).

**Comment by supervacuus** [comment]
> Is there a plan to fix this in the future? (I guess that just having a flag file like the `user-consent` one might help for all platforms).

Yes, we want to fix this; the problem is in `crashpad`. We already added a handler in our `crashpad` fork for Windows, and we will add one for macOS, but the implementation is more involved. It is a relatively high priority since it is one of the last issues preventing the adoption of `crashpad` on all platforms.
