### ISSUE TITLE
Inconsistency in StartHandlerAtCrash Interface Declaration Compared to Original Project

### ISSUE THREAD

**Issue by weypro** [getsentry/sentry-native#937]
Hello. I have been trying to compile the CMake-wrapped version of Crashpad provided by Sentry, to use independently in my own project. I noticed that the StartHandlerAtCrash interface has an additional `http_proxy` parameter compared to the original code, which makes it incompatible with the original Crashpad code. I am curious about the reasoning behind this design choice. Why not add an optional parameter at the end, or introduce a separate interface to maintain compatibility with others?

**Comment by supervacuus** [comment]
The straightforward but maybe unsatisfying answer to your question is that we maintain Sentry's `crashpad` fork solely for the needs and affordances of Sentry's Native SDK. Conceptually, no direct user of our `crashpad` fork requires us to maintain interface compatibility with upstream or any other fork, as we do not expose the interfaces of our crash backends to users of the Native SDK.

Having said that, if it turns out we broke something, we are open to accepting PRs or even providing fixes ourselves (if the effort is low), even though we do not see interfaces in our fork as a contract beyond the Native SDK. We will break things in the future, so we do not separately version or release our crashpad fork and only add changes in lock-step with the Native SDK release. The upstream repository might serve you better if you need a stable interface.
