### ISSUE TITLE
Allow MIME detection for crashpad attachments in the backend

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry-native#955]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Attach a JSON file and try to view it within the issue page. The preview option is greyed out with the text: `Attachment cannot be previewed`

A user got around this by adding `contentType`. 
It's a property on the attachment object
const filename = 'XXX.json';
const contentType = 'application/json'; // helps show Preview in Sentry
hint.attachments = hint.attachments || [];
hint.attachments.push({ filename, data, contentType });

We should try to derive the content type from the file name. 

### Expected Result

Can view the payload in the issue. 

### Actual Result

<img width="1160" alt="Screenshot 2023-10-11 at 4 30 07 PM" src="https://github.com/getsentry/sentry/assets/89524511/caa6bdf0-3dc4-4719-86a3-aac543570ba3">

### Product Area

Issues

**Comment by Swatinem** [comment]
> We have checked the suggested approach and we do not see how we can set content type for crash reports attachment, there is no such API in sentry.h. We have tried to set it in the Sentry SDK source code, we tried to change "application/x-sentry-envelope" to "application/json", but that did not help. See: https://github.com/getsentry/sentry-native/blob/master/src/sentry_transport.c#L8

You are right, there currently is no API to set an explicit content-type for attachments.

Also the code you pointed to is completely different, and you should not change the `application/x-sentry-envelope` value.

An *envelope* includes all the metadata related to an event, with different items. Things like the event JSON payload, attachments, sessions, etc.

That being said, attachments are very bare-bones right now, and only really have a file path you register them with and thats it. Adding more metadata to it is possible, but would either inflate the API surface by adding new functions, or a breaking change which is a lot less likely.

**Comment by supervacuus** [comment]
This is a direct result of https://github.com/getsentry/sentry-native/issues/894

Adding interfaces is the right choice here, but we also need to extend `crashpad`, which currently doesn't support attachment content types being passed to the handler.

cc: @kahest (prioritization?)

**Comment by kahest** [comment]
Closing this as the work required to fix this is captured in #894 - which currently has medium priority, but we'll revisit if we want to bump prio.

**Comment by kahest** [comment]
@supervacuus I see - does it make sense to track this in this issue separately?

**Comment by supervacuus** [comment]
I think it does because it means that our attachments are generally MIME-detected and don't require our users to provide a content type manually. 

The other ticket might still make sense for the latter, but I think most users would be happy with the MIME detection in the backend if it actually runs rather than having to provide a content type for each attachment. So, #894 is more work and a less valuable feature.

So, the issue boils down to: 

* why don't we get the MIME detection for crashpad events?
* is it because the `crashpad_handler` does something wrong when attaching to multipart?

I know that the `crashpad_handler` sends all attachments as `application/octet-stream` while we do not add any `Content-Type` header to the envelope items that are attachments. So removing the `Content-Type` from the attachments sent from the `crashpad_handler` could do the trick.

Also, after a quick search in the backend, it seems like an attachment without a `Content-Type` header is the correct discriminator for automatic detection (cc: @Swatinem):

https://github.com/getsentry/sentry/blob/baaf0f404af0229334691f1ed4701950600f0de8/src/sentry/api/serializers/models/eventattachment.py#L39-L43

https://github.com/getsentry/sentry/blob/42050bfa4f3fcc6b19c9f104eba868dcc8535eaa/src/sentry/models/eventattachment.py#L184-L187

I have no way of seeing how attachments are processed, though, so I would need support from an employee when testing this.

If it turns out we can fix this at that point, I think it would be an extremely valuable fix and little effort.

**Comment by kahest** [comment]
As discussed:
- Can we strip out the `application/octet-stream`? (in Relay or Crashpad handler)
- Would this make automatic mime type detection work?

Next step: Let's adapt Crashpad handler and test this locally

**Comment by kahest** [comment]
related Relay PR: https://github.com/getsentry/relay/pull/3225

**Comment by aallrd** [comment]
Hello,
I bumped into this issue playing with the `sentry_options_add_attachment()` API to send an AddressSanitizer log file with the minidump.
I tried to add the `.txt` extension to the file name but the preview button was still greyed out in the UI.
I guess it would need to be sent with the `text/plain` _contentType_.

**Comment by supervacuus** [comment]
Hi @aallrd, We are currently working on integrating a change to the pipeline that would let attachment MIME detection run in the backend without you having to specify a content type in the SDK or change the file extension.
