### ISSUE TITLE
Set user agent string (sdk name + version)

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-native#957]
Currently, the SDK only sets the `x-sentry-auth` field in the transport:

https://github.com/getsentry/sentry-native/blob/2ae5de657086c92b0101a51bd85f3dab72b36bf1/src/sentry_transport.c#L193

To align with https://github.com/getsentry/team-sdks/issues/61, we want to send the SDK name and version as `User-Agent` using the format `<sdk-name>/<sdk-version>`.

TBD: crashpad/breakpad

**Comment by supervacuus** [comment]
Hi @kahest 

> Currently, the SDK only sets the `x-sentry-auth` field in the transport:

This is not true. We also set the user-agent to `sdk_name/version`:

https://github.com/getsentry/sentry-native/blob/master/src/sentry_options.c#L322-L329

Since `breakpad` uses the same transport as any other envelope, this is also true with minidumps from `breakpad`.

With `crashpad`, the current solution is to append the `sentry_client` as part of a set of [X-Sentry-Auth](https://develop.sentry.dev/sdk/overview/#authentication) query parameters with the minidump request. The format is the same as with the user-agent above.

**Comment by kahest** [comment]
@supervacuus I see that this constructs `opts->user_agent` with name and version, but I couldn't find where this is used to set a user agent header on the transport, but I guess I looked at the wrong place - is this the relevant code?

https://github.com/getsentry/sentry-native/blob/2ae5de657086c92b0101a51bd85f3dab72b36bf1/src/transports/sentry_transport_curl.c#L105
https://github.com/getsentry/sentry-native/blob/2ae5de657086c92b0101a51bd85f3dab72b36bf1/src/transports/sentry_transport_winhttp.c#L66

**Comment by kahest** [comment]
@supervacuus Perfect, thanks for confirming - closing this now

**Comment by supervacuus** [comment]
Similarly, the minidump URL for crashpad is constructed from the DSN and the user-agent. That should also make it clearly visible when checking LB issues.
