### ISSUE TITLE
Breadcrumb Duplication for Multi-Transaction Applications

### ISSUE THREAD

**Issue by jerin-omcare** [getsentry/sentry-native#991]
I am getting duplicate breadcrumbs between transactions in my Qt application using sentry-native SDK. 

From my understanding, in the current implementation of Sentry's Qt integration, the default logger captures log messages as breadcrumbs and adds them to a global list. This list persists until `sentry_close()` is called. This leads to issues when using transactions:

- Breadcrumbs from previous transactions are included in subsequent transactions.
- For applications involving multiple distinct transactions, this results in duplicated breadcrumbs.
- Irrelevant breadcrumb entries are sent with each transaction, cluttering the data.

Ideally, breadcrumbs should be scoped to the current transaction. This would ensure only relevant breadcrumbs are captured and sent with each transaction.

**Comment by supervacuus** [comment]
Hi @jerin-omcare, thanks for the report. I can understand why this seems illogical. At this point, the Native SDK treats `transactions` like any other `event` when applying the scope before capturing. The only difference is that we don't send a stack trace and module list with each transaction.

But it would make sense to only add breadcrumbs to transactions where the timestamp is within the transaction boundaries. Would this solve your current issue? I still have to ensure that this correlates with the expected behavior of the API or, rather, the implementations in other SDKs.

**Comment by jerin-omcare** [comment]
> But it would make sense to only add breadcrumbs to transactions where the timestamp is within the transaction boundaries. Would this solve your current issue? I still have to ensure that this correlates with the expected behavior of the API or, rather, the implementations in other SDKs.

@supervacuus This makes sense and I agree that adding breadcrumbs only to transactions within the transaction boundaries would indeed resolve the current issue.

**Comment by kahest** [comment]
Hey @jerin-omcare thanks for writing in - the behaviour you describe is intentional. 

The goal of breadcrumbs is to give context information of events that happened before or during a transaction, and can include a variety of data (e.g. changes in network state, http requests, apps becoming active or going into background, etc.). Many of these events are relevant for transactions even though they happen outside (before) the time frame of the transaction. Therefore all our SDKs do **not** scope breadcrumbs to specific transactions.

You can read more about how we envision breadcrumbs to be used in the [docs](https://docs.sentry.io/product/issues/issue-details/breadcrumbs/) and in our [develop docs](https://develop.sentry.dev/sdk/features/#breadcrumbs).

**Comment by tiny-dancer** [comment]
@kahest thank you for the response, we've observed the breadcrumbs are queued and added all the way back to app start up depending on our configured breadcrumb limit.  Is there a built in mechanism to ensure the global breadcrumb size doesn't grow forever?

**Comment by kahest** [comment]
@tiny-dancer there is a limit which can be configured via `max_breadcrumbs` and defaults to 100 ([docs](https://docs.sentry.io/platforms/native/configuration/options/#max-breadcrumbs)). If you can reproduce an issue with the SDK exceeding this limit, please [open up a separate issue](https://github.com/getsentry/sentry-native/issues/new/choose) 🙏
